website/report/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('report.views',
    url(r'^$', 'index', name='index'),
    url(r'^excel-reports/(?P<category>.*)/$', 'excel_reports', name='excel_reports'),
    url(r'^add/district/$', 'add_district', name='add_district'),
    url(r'^add/block/$', 'add_block', name='add_block'),
    url(r'^add/health-center/$', 'add_health_center', name='add_health_center'),
    url(r'^add/event/$', 'add_event', name='add_event'),
    url(r'^edit/district/$', 'district_list_edit', name='district_list_edit'),
    url(r'^edit/district/(?P<district_name>.*)/$', 'edit_district', name='edit_district'),
    url(r'^delete/district/(?P<district_name>.*)/$', 'delete_district', name='delete_district'),

    url(r'^edit/block/$', 'block_list_edit', name='block_list_edit'),
    url(r'^edit/block/(?P<block_name>.*)/$', 'edit_block', name='edit_block'),
    url(r'^delete/block/(?P<block_name>.*)/$', 'delete_block', name='delete_block'),

    url(r'^edit/health-center/$', 'health_center_list_edit', name='health_center_list_edit'),
    url(r'^edit/health-center/(?P<health_center_name>.*)/$', 'edit_health_center', name='edit_health_center'),
    url(r'^delete/health-center/(?P<health_center_name>.*)/$', 'delete_health_center', name='delete_health_center'),
    url(r'^feeds/block-by-district-name/(?P<district_name>.*)/$', 'feeds_block_list', name='feeds_block_list'),
    url(r'^feeds/district-center/(?P<district_name>.*)/$', 'feeds_district_center', name='feeds_district_center'),
    url(r'^feeds/block-center/(?P<block_name>.*)/$', 'feeds_block_center', name='feeds_block_center'),
    url(r'^feeds/health-center-position/(?P<block_name>.*)/$', 'feeds_block_center', name='feeds_block_center'),
)

website/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.shortcuts import render_to_response
from django.views.generic.simple import direct_to_template

import settings

admin.autodiscover()

urlpatterns = patterns('',
                       (r'^admin/', include(admin.site.urls)),
                       (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'main/login.html'}),
                       (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'main/logout.html'}),
                       (r'^about/$', 'direct_to_template', {"template": "main/about.html"}),
                       (r'^', include("report.urls")),
)
if settings.DEBUG:
    # Set
    mediaURL = settings.MEDIA_URL[1:]
    # Extend
    urlpatterns += patterns('',
        (r'^%s(?P<path>.*)$' % mediaURL, 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

website/report/models.py
from django.db import models
from report.widgets import *

class District(models.Model):
    name = models.CharField("Name", max_length=100)
    center = LocationField("Position of center", blank=False, max_length=255)
    
    def __unicode__(self):
        return self.name
    
class Block(models.Model):
    name = models.CharField("Name", max_length=100)
    district = models.ForeignKey(District)
    center = LocationField("Position of center", blank=True, max_length=255)
    
    def __unicode__(self):
        return self.name

class HealthCenter(models.Model):
    code = models.IntegerField("4 digit code", max_length=4, unique=True)
    name = models.CharField("Name", max_length=100)
    district = models.ForeignKey(District)
    block = models.ForeignKey(Block)
    center = LocationField("Position on map", blank=True, max_length=255)
    
    # GeoDjango-specific: a geometry field (MultiPolygonField), and
    # overriding the default manager with a GeoManager instance.
    #objects = models.GeoManager()
    
    # So the model is pluralized correctly in the admin.
    class Meta:
        verbose_name = "Health Center"
        verbose_name_plural = "Health Centers"

    # Returns the string representation of the model.
    def __unicode__(self):
        return self.name

class Event(models.Model):
    CATEGORY_CHOICES = (
    (1, 'Category 1'),
    (2, 'Category 2'),
    (3, 'Category 3'),
    )

    reporting_date = models.DateField("Date of reporting")
    reporting_time = models.TimeField("Time of reporting", auto_now=False, auto_now_add=True)
    district = models.ForeignKey(District)
    block = models.ForeignKey(Block)
    target_health_center = models.ForeignKey(HealthCenter)
    category = models.IntegerField("Category", max_length=1, choices=CATEGORY_CHOICES)
    money = models.IntegerField("Amount of money")
    
    def __unicode__(self):
        return "Category = "+ str(self.category)+ ", Date = " + str(self.reporting_date) + ", Health Center = " + str(self.target_health_center)+", Money = " + str(self.money)

website/report/forms.py
from django.forms import ModelForm, ChoiceField, Select
from report.models import HealthCenter, District, Block, Event

class HealthCenterForm(ModelForm):
    block = ChoiceField(choices=(('-1', 'Select Block'),))
    class Meta:
        model = HealthCenter

class DistrictForm(ModelForm):
    class Meta:
        model = District

class BlockForm(ModelForm):
    class Meta:
        model = Block
        
class EventForm(ModelForm):
    class Meta:
        model = Event

website/report/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from report.models import Event, Block, District, HealthCenter
from report.forms import DistrictForm, BlockForm, HealthCenterForm, EventForm
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from report.create_excel import ExcelResponse

try:
    from functools import wraps
except ImportError:
    from django.utils.functional import wraps


uttar_pradesh_lat = "26.79644"
uttar_pradesh_lng = "82.198639"
map_zoom_level = 7

@login_required
def index(request):
    events = Event.objects.all()
    return render_to_response('report/index.html', {'events' : events, "center_lat":uttar_pradesh_lat, "center_lng":uttar_pradesh_lng, "zoom_level":map_zoom_level, "map_api_key":settings.MAPS_API_KEY},context_instance=RequestContext(request))

@login_required
def add_district(request):
    if request.POST:
        f = DistrictForm(request.POST)
        if f.is_valid():
            f.save()
            return render_to_response('report/add_district_done.html',)
    else:
         f = DistrictForm()   
    return render_to_response('report/add_district.html', {"form":f, "center_lat":uttar_pradesh_lat, "center_lng":uttar_pradesh_lng, "zoom_level":map_zoom_level, "map_api_key":settings.MAPS_API_KEY},context_instance=RequestContext(request))

@login_required
def add_block(request):
    if request.POST:
        f = BlockForm(request.POST)
        if f.is_valid():
            f.save()
            return render_to_response('report/add_block_done.html',)
    else:
         f = BlockForm()   
    return render_to_response('report/add_block.html', {"form":f, "center_lat":uttar_pradesh_lat, "center_lng":uttar_pradesh_lng, "zoom_level":map_zoom_level, "map_api_key":settings.MAPS_API_KEY},context_instance=RequestContext(request))

@login_required
def add_health_center(request):
    if request.POST:
        f = HealthCenterForm(request.POST)
        if f.is_valid():
            f.save()
            return render_to_response('report/add_health_center_done.html',)
    else:
         f = HealthCenterForm()   
    return render_to_response('report/add_health_center.html', {"form":f, "center_lat":uttar_pradesh_lat, "center_lng":uttar_pradesh_lng, "zoom_level":map_zoom_level, "map_api_key":settings.MAPS_API_KEY},context_instance=RequestContext(request))

@login_required
def add_event(request):
    if request.POST:
        f = EventForm(request.POST)
        if f.is_valid():
            f.save()
            return render_to_response('report/add_event_done.html',)
    else:
         f = EventForm()   
    return render_to_response('report/add_event.html', {"form":f, "center_lat":uttar_pradesh_lat, "center_lng":uttar_pradesh_lng, "zoom_level":map_zoom_level, "map_api_key":settings.MAPS_API_KEY},context_instance=RequestContext(request))

@login_required
def feeds_block_list(request, district_name):
    block_list = Block.objects.all().filter(district=get_object_or_404(District, name=district_name)).order_by("id")
    return render_to_response('feeds/blocks.txt', {'block_list':block_list, }, mimetype="text/plain")

@login_required
def feeds_district_center(request, district_name):
    district = get_object_or_404(District, name=district_name)
    return HttpResponse(district.center)

@login_required
def feeds_block_center(request, block_name):
    block = get_object_or_404(Block, name=block_name)
    return HttpResponse(block.center)

@login_required
def feeds_health_center_position(request, health_center_name):
    hc = get_object_or_404(HealthCenter, name=health_center_name)
    return HttpResponse(hc.center)


def confirm_required(template_name, context_creator, key='__confirm__'):
    def decorator(func):
        def inner(request, *args, **kwargs):
            if request.POST.has_key(key):
                return func(request, *args, **kwargs)
            else:
                context = context_creator and context_creator(request, *args, **kwargs) \
                    or RequestContext(request)
                return render_to_response(template_name, context)
        return wraps(func)(inner)
    return decorator

@login_required
def district_list_edit(request):
    d_list = District.objects.all().order_by('name')
    return render_to_response("report/district_list_edit.html", {"districts":d_list})

@login_required
def edit_district(request, district_name):
    if request.POST:
        f = DistrictForm(request.POST)
        if f.is_valid():
            f.save()
            return render_to_response('report/edit_district_done.html',)
    else:
         f = DistrictForm(instance = get_object_or_404(District, name=district_name))   
    return render_to_response('report/edit_district.html', {"form":f, "center_lat":uttar_pradesh_lat, "center_lng":uttar_pradesh_lng, "zoom_level":map_zoom_level, "map_api_key":settings.MAPS_API_KEY},context_instance=RequestContext(request))


@login_required
def delete_district_context(request, district_name):
    d = get_object_or_404(District, name=district_name)
    return RequestContext(request, {'district': d})

@confirm_required('report/delete_district_confirm.html', delete_district_context)
@login_required
def delete_district(request, district_name):
    d = get_object_or_404(District, name=district_name)
    d.delete()
    next_url = request.GET.get('next', '/edit/district/')
    return HttpResponseRedirect(next_url)


@login_required
def block_list_edit(request):
    b_list = Block.objects.all().order_by('name')
    return render_to_response("report/block_list_edit.html", {"blocks":b_list})

@login_required
def edit_block(request, block_name):
    if request.POST:
        f = BlockForm(request.POST)
        if f.is_valid():
            f.save()
            return render_to_response('report/edit_block_done.html',)
    else:
         f = BlockForm(instance = get_object_or_404(Block, name=block_name))   
    return render_to_response('report/edit_block.html', {"form":f, "center_lat":uttar_pradesh_lat, "center_lng":uttar_pradesh_lng, "zoom_level":map_zoom_level, "map_api_key":settings.MAPS_API_KEY},context_instance=RequestContext(request))

@login_required
def delete_block_context(request, block_name):
    b = get_object_or_404(Block, name=block_name)
    return RequestContext(request, {'block': b})

@confirm_required('report/delete_block_confirm.html', delete_block_context)
@login_required
def delete_block(request, block_name):
    d = get_object_or_404(Block, name=block_name)
    d.delete()
    next_url = request.GET.get('next', '/edit/block/')
    return HttpResponseRedirect(next_url)

@login_required
def health_center_list_edit(request):
    hc_list = HealthCenter.objects.all().order_by('name')
    return render_to_response("report/health_center_list_edit.html", {"health_centers":hc_list})

@login_required
def edit_health_center(request, health_center_name):
    if request.POST:
        f = HealthCenterForm(request.POST)
        if f.is_valid():
            f.save()
            return render_to_response('report/edit_health_center_done.html',)
    else:
         f = HealthCenterForm(instance = get_object_or_404(HealthCenter, name=health_center_name))   
    return render_to_response('report/edit_health_center.html', {"form":f, "center_lat":uttar_pradesh_lat, "center_lng":uttar_pradesh_lng, "zoom_level":map_zoom_level, "map_api_key":settings.MAPS_API_KEY},context_instance=RequestContext(request))

@login_required
def delete_health_center_context(request, health_center_name):
    hc = get_object_or_404(HealthCenter, name=health_center_name)
    return RequestContext(request, {'health_center': hc})

@confirm_required('report/delete_health_center_confirm.html', delete_health_center_context)
@login_required
def delete_health_center(request, health_center_name):
    d = get_object_or_404(HealthCenter, name=health_center_name)
    d.delete()
    next_url = request.GET.get('next', '/edit/health-center/')
    return HttpResponseRedirect(next_url)

def excel_reports(request, category):
    if category == '0':
        objs = Event.objects.all().order_by("id")
    else:
        objs = Event.objects.all().filter(category = int(category)).order_by("id")
    data_list = [
        ["Date","Time", "Health Center", "Block", "District", "Category", "Amount"],
        ]

    for o in objs:
        data_list.append(
            [o.reporting_date,o.reporting_time, o.target_health_center.name, o.block.name, o.district.name, o.category, o.money]
            )

    return ExcelResponse(data_list)

website/templates/report/add_block.html
{% extends 'base.html' %}
{% block title %}Add Block{% endblock %}
{% block extra_head %}
<script type="text/javascript">
    $(document).unload(function(){
        GUnload();
    });
    
    $(document).ready(function(){
        $("<div id=\"map_canvas\" class=\"location_picker_map\"></div>").insertBefore($("input.location_picker"));
        //$("input.location_picker").css("display", "none")
        var lat = "{{ center_lat }}";
        var lng = "{{ center_lng }}";
        var center = new GLatLng(lat, lng);
        var zoom_level = parseInt("{{ zoom_level }}");
        var map = new GMap2(document.getElementById("map_canvas"));
		map.setCenter(center, zoom_level);
        map.addControl(new GLargeMapControl());
        map.addControl(new GMapTypeControl());
        
        var marker = new GMarker(center, {draggable: true});
		map.addOverlay(marker);
        GEvent.addListener(marker, 'dragend', function(){
            $("#id_center").attr("value", marker.getLatLng().lat() + ',' + marker.getLatLng().lng());
        });
        function updateMarker(location){
            marker.setLatLng(location);
            $("#id_center").attr("value", marker.getLatLng().lat() + ',' + marker.getLatLng().lng());
            map.setCenter(location);
        }    
        
        $("#id_district").change(function(){
            filterBlocks($("#id_district").val());
        }).change();
        
        function filterBlocks(){
            $.get("/feeds/district-center/" + $("#id_district :selected").text() + "/", function(data){
                map.setCenter(new google.maps.LatLng(data.split(",")[0], data.split(",")[1]));
                map.setZoom(zoom_level + 4);
                updateMarker(new GLatLng(map.getCenter().lat(), map.getCenter().lng()));
            });
        };        
        });
</script>
{% endblock %}
{% block content %}<h2>Add Block</h2>
<p>
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td>
                    <input type="submit" value="Submit"/>
                </td>
            </tr>
        </table>
    </form>
</p>{% endblock %}

website/templates/report/add_block_done.html
{% extends 'base.html' %}
{% block title %}Add Block{% endblock %}
{% block content %}<h2>Add Block</h2>
<p>
	Block Details were added successfully.
</p>{% endblock %}

website/templates/report/add_event.html
{% extends 'base.html' %}
{% block title %}Add Event{% endblock %}
{% block extra_head %}
<script type="text/javascript">
    $(document).unload(function(){
        GUnload();
    });
    
    $(document).ready(function(){
        $("<div id=\"map_canvas\" class=\"location_picker_map\"></div>").insertBefore($("input.location_picker"));
        //$("input.location_picker").css("display", "none")
        var lat = "{{ center_lat }}";
        var lng = "{{ center_lng }}";
        var center = new google.maps.LatLng(lat, lng);
        var zoom_level = parseInt("{{ zoom_level }}");
        var mapOptions = {
            zoom: zoom_level,
            center: center,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
        
        var marker = new google.maps.Marker({
            position: center,
            map: map,
            draggable: true,
            animation: google.maps.Animation.DROP,
            title: ""
        });
        google.maps.event.addListener(map, 'click', function(event){
            updateMarker(event.latLng);
        });
        google.maps.event.addListener(marker, 'dragend', markerDragged);
        google.maps.event.addListener(marker, 'click', toggleBounce);
        
        function updateMarker(location){
            marker.setPosition(location);
            $("#id_center").attr("value", marker.getPosition().lat() + ',' + marker.getPosition().lng());
            //map.setCenter(location);
        }
        
        function toggleBounce(){
            if (marker.getAnimation() != null) {
                marker.setAnimation(null);
            }
            else {
                marker.setAnimation(google.maps.Animation.BOUNCE);
            }
        };
        
        function markerDragged(){
            //alert("was called" + marker.getPosition());
            $("#id_center").attr("value", marker.getPosition().lat() + ',' + marker.getPosition().lng());
            //map.setCenter(marker.getPosition(), zoom_level + 1);
        }
        
        $("#id_district").change(function(){
            filterBlocks($("#id_district").val());
        }).change();
        $("#id_block").html("<option value=\"0\">Select district first</option>");
        
        function filterBlocks(){
            $.get("/feeds/district-center/"+$("#id_district :selected").text()+"/", function(data){
                map.setCenter(new google.maps.LatLng(data.split(",")[0], data.split(",")[1]));
				map.setZoom(zoom_level + 6);
				updateMarker(new google.maps.LatLng(map.getCenter().lat(), map.getCenter().lng()));
            });            
            var url = "/feeds/block-by-district-name/"
            url += $("#id_district :selected").text();
            url += "/";
			$("#id_block").html("<option value=\"0\">Loading from database ...</option>");
			$.get(url, function(data){				
				$("#id_block").html("");
				$("#id_block").html("<option value=\"0\">Select Block</option>"+data);
			})
        };
		
		$("#id_block").change(function(){
            filterHealthCenters($("#id_block").val());
        }).change();
		$("#id_target_health_center").html("<option value=\"0\">Select block first</option>");
		
		function filterHealthCenters(){
            $.get("/feeds/block-center/"+$("#id_block :selected").text()+"/", function(data){
                map.setCenter(new google.maps.LatLng(data.split(",")[0], data.split(",")[1]));
				map.setZoom(zoom_level + 4);
				updateMarker(new google.maps.LatLng(map.getCenter().lat(), map.getCenter().lng()));
            });            
            var url = "/feeds/health-center-by-block-name/"
            url += $("#id_block :selected").text();
            url += "/";
			$("id_target_health_center").html("<option value=\"0\">Loading from database ...</option>");
			$.get(url, function(data){				
				$("id_target_health_center").html("<option value=\"0\">Select Health Center</option>"+data);
			})
        };
		
		$("#id_submit").click(function(e){
			//e.preventDefault();
			alert("Make sure Positon is correct. do you want to save it ?");
			//$("form").submit();
		});
        
        });
</script>
{% endblock %}
{% block content %}<h2>Add Event</h2>
<p>
    <form method="post" action="">
        <table>
            {{ form.as_table }}
            <tr style="padding-left:100;">
                <td>
                    <input id="id_submit" type="submit" value="Submit"/>
                </td>
            </tr>
        </table>
    </form>
</p>{% endblock %}

website/templates/report/add_health_center.html
{% extends 'base.html' %}
{% block title %}Add Health Center{% endblock %}
{% block extra_head %}
<script type="text/javascript">
    $(document).unload(function(){
        GUnload();
    });
    
    $(document).ready(function(){
        $("<div id=\"map_canvas\" class=\"location_picker_map\"></div>").insertBefore($("input.location_picker"));
        //$("input.location_picker").css("display", "none")
        var lat = "{{ center_lat }}";
        var lng = "{{ center_lng }}";
        var center = new GLatLng(lat, lng);
        var zoom_level = parseInt("{{ zoom_level }}");
        var map = new GMap2(document.getElementById("map_canvas"));
		map.setCenter(center, zoom_level);
        map.addControl(new GLargeMapControl());
        map.addControl(new GMapTypeControl());
        
        var marker = new GMarker(center, {draggable: true});
		map.addOverlay(marker);
        GEvent.addListener(marker, 'dragend', function(){
            $("#id_center").attr("value", marker.getLatLng().lat() + ',' + marker.getLatLng().lng());
        });
        function updateMarker(location){
            marker.setLatLng(location);
            $("#id_center").attr("value", marker.getLatLng().lat() + ',' + marker.getLatLng().lng());
            map.setCenter(location);
        }
		
        $("#id_district").change(function(){
            filterBlocks($("#id_district").val());
        }).change();
        $("#id_block").attr('disabled');
        $("#id_block").html("<option value=\"\">Select district first</option>");
        
        function filterBlocks(){
            $.get("/feeds/district-center/"+$("#id_district :selected").text()+"/", function(data){
                map.setCenter(new google.maps.LatLng(data.split(",")[0], data.split(",")[1]));
				map.setZoom(zoom_level + 4);
				updateMarker(new google.maps.LatLng(map.getCenter().lat(), map.getCenter().lng()));
            });            
            var url = "/feeds/block-by-district-name/"
            url += $("#id_district :selected").text();
            url += "/";
			$("#id_block").html("<option value=\"\">Loading from database ...</option>");
			$.get(url, function(data){				
				$("#id_block").html("");
				$("#id_block").html("<option value=\"\">Select Block</option>"+data);
			})
        };
		
		$("#id_block").change(function(){
            zoomForHealthCenters($("#id_block").val());
        }).change();
		
		function zoomForHealthCenters(){
            $.get("/feeds/block-center/"+$("#id_block :selected").text()+"/", function(data){
                map.setCenter(new google.maps.LatLng(data.split(",")[0], data.split(",")[1]));
				map.setZoom(zoom_level + 6);
				updateMarker(new google.maps.LatLng(map.getCenter().lat(), map.getCenter().lng()));
            });
        };
		
		$("#id_submit").click(function(e){
			//e.preventDefault();
			//alert("Make sure Positon is correct. do you want to save it ?");
			//$("form").submit();
		});
        
        });
</script>
{% endblock %}
{% block content %}<h2>Add Health Center</h2>
<p>
    <form method="post" action="">
        <table>
            {{ form.as_table }}
            <tr style="padding-left:100;">
                <td>
                    <input id="id_submit" type="submit" value="Submit"/>
                </td>
            </tr>
        </table>
    </form>
</p>{% endblock %}

website/templates/report/add_health_center_done.html
{% extends 'base.html' %}
{% block title %}Add Health Center{% endblock %}
{% block content %}<h2>Add Health Center</h2>
<p>
	PHC Details were added successfully.
</p>{% endblock %}

website/templates/report/block_list_edit.html
{% extends 'base.html' %}
{% block title %}Edit Districts{% endblock %}
{% block content %}<h2>Select a block to edit or delete</h2>
<p>
	{% for b in blocks %}
    <span style="margin-left:50px;">{{ b.name }}</span><span style="float:right;margin-right:200px;"><a href="/edit/block/{{ b.name }}/">Edit</a><a href="/delete/block/{{ b.name }}/"  style="margin-left:50px;">Delete</a></span><br />
    {% endfor %}
</p>{% endblock %}

website/templates/report/delete_block_confirm.html
{% extends 'base.html' %}
{% block title %}Delete Block{% endblock %}
{% block content %}<h2>Delete block {{ block }}</h2>
<p>
    <form method="POST" action="">
    <p style="color:red">This will delete all health centers associated with block {{ block }}. If you are sure to delete block {{ block }} then press delete otherwsie click on cancel?</p>
        <input type="hidden" name="__confirm__" value="1" />
        <input type="submit" value="Delete"/>
        <a href="/edit/block/" style="color:green">Cancel</a>
    </form>
</p>{% endblock %}

website/templates/report/delete_health_center_confirm.html
{% extends 'base.html' %}
{% block title %}Delete Health Center{% endblock %}
{% block content %}<h2>Delete Health Center {{ health_center }}</h2>
<p>
    <form method="POST" action="">
    <p style="color:red">This will delete all reports associated with health center {{ health_center }}. If you are sure to delete health center {{ health_center }} then press delete otherwsie click on cancel?</p>
        <input type="hidden" name="__confirm__" value="1" />
        <input type="submit" value="Delete"/>
        <a href="/edit/health-center/" style="color:green">Cancel</a>
    </form>
</p>{% endblock %}

website/templates/report/district_list_edit.html
{% extends 'base.html' %}
{% block title %}Edit Districts{% endblock %}
{% block content %}<h2>Select a district to edit</h2>
<p>
	{% for d in districts %}
    <span style="margin-left:50px;">{{ d.name }}</span><span style="float:right;margin-right:200px;"><a href="/edit/district/{{ d.name }}/">Edit</a><a href="/delete/district/{{ d.name }}/"  style="margin-left:50px;">Delete</a></span><br />
    {% endfor %}
</p>{% endblock %}

website/templates/report/edit_district.html
{% extends 'base.html' %}
{% block title %}Edit District{% endblock %}
{% block extra_head %}
<script type="text/javascript">
    $(document).unload(function(){
        GUnload();
    });
    
    $(document).ready(function(){
        $("<div id=\"map_canvas\" class=\"location_picker_map\"></div>").insertBefore($("input.location_picker"));
        //$("input.location_picker").css("display", "none")
        var lat = "{{ center_lat }}";
        var lng = "{{ center_lng }}";
        var center = new GLatLng(lat, lng);
        var zoom_level = parseInt("{{ zoom_level }}");
        var map = new GMap2(document.getElementById("map_canvas"));
		map.setCenter(center, zoom_level);
        map.addControl(new GLargeMapControl());
        map.addControl(new GMapTypeControl());
        
        var marker = new GMarker(center, {draggable: true});
		map.addOverlay(marker);
        GEvent.addListener(marker, 'dragend', function(){
            $("#id_center").attr("value", marker.getLatLng().lat() + ',' + marker.getLatLng().lng());
        });
        function updateMarker(location){
            marker.setLatLng(location);
            $("#id_center").attr("value", marker.getLatLng().lat() + ',' + marker.getLatLng().lng());
            map.setCenter(location);
        }
    });
</script>
{% endblock %}
{% block content %}<h2>Edit District</h2>
<p>
    <form method="post" action="">
        <table>
            {{ form.as_table }}
            <tr style="padding-left:100;">
                <td>
                    <input type="submit" value="Submit"/>
                </td>
            </tr>
        </table>
    </form>
</p>{% endblock %}

website/templates/report/edit_district_done.html
{% extends 'base.html' %}
{% block title %}Edit District{% endblock %}
{% block content %}<h2>Edit District</h2>
<p>
	District was edited successfully.
</p>{% endblock %}

website/templates/report/edit_health_center.html
{% extends 'base.html' %}
{% block title %}Edit Health Center{% endblock %}
{% block extra_head %}
<script type="text/javascript">
    $(document).unload(function(){
        GUnload();
    });
    
    $(document).ready(function(){
        $("<div id=\"map_canvas\" class=\"location_picker_map\"></div>").insertBefore($("input.location_picker"));
        //$("input.location_picker").css("display", "none")
        var lat = "{{ center_lat }}";
        var lng = "{{ center_lng }}";
        var center = new GLatLng(lat, lng);
        var zoom_level = parseInt("{{ zoom_level }}");
        var map = new GMap2(document.getElementById("map_canvas"));
		map.setCenter(center, zoom_level);
        map.addControl(new GLargeMapControl());
        map.addControl(new GMapTypeControl());
        
        var marker = new GMarker(center, {draggable: true});
		map.addOverlay(marker);
        GEvent.addListener(marker, 'dragend', function(){
            $("#id_center").attr("value", marker.getLatLng().lat() + ',' + marker.getLatLng().lng());
        });
        function updateMarker(location){
            marker.setLatLng(location);
            $("#id_center").attr("value", marker.getLatLng().lat() + ',' + marker.getLatLng().lng());
            map.setCenter(location);
        }
    });
</script>
{% endblock %}
{% block content %}<h2>Edit Health Center</h2>
<p>
    <form method="post" action="">
        <table>
            {{ form.as_table }}
            <tr style="padding-left:100;">
                <td>
                    <input type="submit" value="Submit"/>
                </td>
            </tr>
        </table>
    </form>
</p>{% endblock %}

website/templates/report/health_center_list_edit.html
{% extends 'base.html' %}
{% block title %}Edit Health Centers{% endblock %}
{% block content %}<h2>Select a health center to edit or delete</h2>
<p>
	{% for hc in health_centers %}<span style="margin-left:50px;">{{ hc.name }}</span><span style="float:right;margin-right:200px;"><a href="/edit/health-center/{{ hc.name }}/">Edit</a><a href="/delete/health-center/{{ hc.name }}/"  style="margin-left:50px;">Delete</a></span><br />{% endfor %}
</p>{% endblock %}